# Generated by Django 5.2.1 on 2025-12-16 14:50

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(default=dict, help_text='User preferences JSON (autoShift, showMinimap, layoutMode, etc.)')),
                ('metadata', models.JSONField(default=dict, help_text='Per-key metadata for conflict resolution (updated_at, client_op_id per key)')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Preferences',
                'verbose_name_plural': 'User Preferences',
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['data'], name='users_up_data_gin'), django.contrib.postgres.indexes.GinIndex(fields=['metadata'], name='users_up_metadata_gin')],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metadata', models.JSONField(default=dict, help_text='Profile-level metadata for conflict resolution')),
                ('points', models.PositiveIntegerField(default=0, help_text='User points/score (future gamification)')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['metadata'], name='users_userprofile_metadata_gin')],
            },
        ),
    ]
