# Generated by Django 5.2.1 on 2025-12-16 14:50

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('message', models.TextField()),
                ('feedback_type', models.CharField(choices=[('Contact', 'Contact'), ('Follow', 'Follow'), ('Other', 'Other')], default='Other', max_length=20)),
                ('feedback_category', models.CharField(choices=[('Feedback', 'Feedback'), ('Partnership', 'Partnerships'), ('General', 'General enquiry'), ('Support', 'I need help with something'), ('Other', 'Something Else'), ('flag_incorrect', 'Incorrect or outdated information'), ('flag_inappropriate', 'Inappropriate or unsafe content'), ('flag_off_topic', 'Off-topic or irrelevant content'), ('flag_bug', 'Bug or technical issue'), ('flag_other', 'Other')], default='Other', max_length=20)),
                ('target', models.CharField(blank=True, max_length=255)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Feedback',
                'verbose_name_plural': 'Feedback',
                'ordering': ['-date_created'],
            },
        ),
    ]
