"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from decimal import Decimal, InvalidOperation
from pathlib import Path

import dj_database_url
import sentry_sdk

from config.env_settings import settings

BASE_DIR = settings.base_dir

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = settings.secret_key

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = settings.debug

BASE_URL = getattr(settings, "base_url", "https://example.com").rstrip("/")

ALLOWED_HOSTS = settings.allowed_hosts
CSRF_TRUSTED_ORIGINS = [f"https://{host}" for host in ALLOWED_HOSTS if not host.startswith("localhost")]

# Add development origins for CSRF in DEBUG mode
if DEBUG:
    CSRF_TRUSTED_ORIGINS.extend([
        "http://localhost:5173",  # Vite dev server
    ])

# CORS configuration.
# For Prod, all web + API requests will be on a single domain.
CORS_ALLOW_ALL_ORIGINS = False
if DEBUG:
    # For local development, allow access to Svelte app (Vite) on port 5173.
    CORS_ALLOWED_ORIGINS = [
        "http://localhost:5173",
    ]
    # Allow credentials for session authentication in dev
    CORS_ALLOW_CREDENTIALS = True
else:
    CORS_ALLOWED_ORIGINS = []
    CORS_ALLOW_CREDENTIALS = False


# Application definition
INSTALLED_APPS = [
    "jazzmin",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sitemaps",
    "django.contrib.postgres",
    "segno",
    "corsheaders",
    "parler",
    "config",
    "core",
    "pages",
    "payments",
    "users",
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "allauth.socialaccount.providers.google",
    "crispy_forms",
    "crispy_daisyui",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "core.middleware.AuthStateCookieMiddleware",
    "allauth.account.middleware.AccountMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "django.middleware.locale.LocaleMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "config.context_processors.default_metadata",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"

AUTH_STATE_COOKIE_NAME = "traders_auth"
AUTH_STATE_COOKIE_SAMESITE = "Lax"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': dj_database_url.config(default=os.environ.get("DATABASE_URL"))
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
        "OPTIONS": {
            "min_length": 6,
        },
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-gb"

TIME_ZONE = "Africa/Johannesburg"

USE_I18N = True

USE_TZ = True

CELERY_BROKER_URL = settings.celery_broker_url
CELERY_RESULT_BACKEND = settings.celery_result_backend
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = TIME_ZONE
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True
CELERY_TASK_DEFAULT_QUEUE = getattr(settings, "celery_task_default_queue", "default")
CELERY_TASK_ALWAYS_EAGER = getattr(settings, "celery_task_always_eager", False)

SLACK_WEBHOOK_APP_FEEDBACK = getattr(settings, "slack_webhook_app_feedback", "")

# Multilingual setup.
LANGUAGES = [
    ('en-gb', 'English'),
    ('af', 'Afrikaans'),
    # Future languages to be added here.
]
PARLER_LANGUAGES = {
    None: (
        {'code': 'en-gb'},
        {'code': 'af'},
    ),
    'default': {
        'fallback': 'en-gb',
        'hide_untranslated': False,
    }
}

# REST / API Settings and flooding protection.
REST_FRAMEWORK = {
    "DEFAULT_RENDERER_CLASSES": [
        "rest_framework.renderers.JSONRenderer",
    ],
    "DEFAULT_PARSER_CLASSES": [
        "rest_framework.parsers.JSONParser",
    ],
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.UserRateThrottle",
        "rest_framework.throttling.ScopedRateThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {
        "user": "360/hour",
        "feedback_anon": "3/hour",
    }
}


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATICFILES_DIRS = [
    BASE_DIR / "static",                     # CSS / JS / images
    BASE_DIR / settings.content_local_path,  # Git content repository
]
STATIC_ROOT = BASE_DIR / "staticfiles"    # For collectstatic (prod)
# We use WhiteNoise for serving static files where Debug is False (e.g. Production).
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.db.DatabaseCache",
        "LOCATION": getattr(settings, "cache_table_name", "django_cache"),
        "TIMEOUT": getattr(settings, "cache_timeout_seconds", None),
        "OPTIONS": {
            "MAX_ENTRIES": getattr(settings, "cache_max_entries", 10000),
        },
    },
}

SEGNO_DEFAULTS = getattr(settings, "segno_defaults", {"error": "q"})
QR_CODE_BASE_URL = getattr(settings, "qr_code_base_url", "https://example.com")
QR_CODE_SCALE = getattr(settings, "qr_code_scale", 6)
QR_CODE_CACHE_TIMEOUT = getattr(settings, "qr_code_cache_timeout", 60 * 60 * 24 * 30)

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Custom admin path used by config/urls.py.
ADMIN_URL = "admin/"

## SMTP Configuration
DEFAULT_FROM_EMAIL = "Traders Team <hello@example.com>"
DEFAULT_CONTACT_EMAIL = settings.default_contact_email
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_PORT = 2587 # We use non-standard port as some hosts block 587.
EMAIL_USE_TLS = True
EMAIL_HOST = settings.smtp_host
EMAIL_HOST_USER = settings.smtp_host_user
EMAIL_HOST_PASSWORD = settings.smtp_host_password

# Content repository and associated local path for syncing content.
CONTENT_REPOSITORY_URL = settings.content_repository_url
CONTENT_LOCAL_PATH = settings.content_local_path

## Payments integration using PayStack.
PAYSTACK_PUBLIC_KEY = settings.paystack_public_key
PAYSTACK_SECRET_KEY = settings.paystack_secret_key
PAYSTACK_PLAN_CODE_MAP = {
    "tier-1": {
        "monthly": "PLN_lby7jikgcii1d1f",
    },
}

EXCHANGE_RATE_API_URL = getattr(settings, "exchange_rate_api_url", "https://api.frankfurter.app/latest")
EXCHANGE_RATE_DISPLAY_URL = getattr(
    settings,
    "exchange_rate_display_url",
    "https://www.xe.com/currencyconverter/convert/?Amount=1&From=USD&To=ZAR",
)
try:
    EXCHANGE_RATE_FALLBACK = Decimal(str(getattr(settings, "exchange_rate_fallback", "0.05")))
except (InvalidOperation, TypeError):
    EXCHANGE_RATE_FALLBACK = Decimal("0.05")

TURNSTILE_SITE_KEY = settings.turnstile_site_key
TURNSTILE_SECRET_KEY = settings.turnstile_secret_key

SITE_META = {
    "site_name": "Traders",
    "default_title": "Traders",
    "default_description": (
        "We enable small traders to provide their services efficiently."
    ),
    "default_og_image": f"{STATIC_URL}images/traders-icon.png",
    "default_robots": "index,follow",
    "append_site_name": True,
}

## User account configuration - Allauth / Google.
SITE_ID = 1
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]
# Email is the primary identifier.
ACCOUNT_LOGIN_METHODS = {"email"}
# Fields used at sign up (email required, no username).
ACCOUNT_SIGNUP_FIELDS = [
    "email*",
    "password1*",
    "password2*",
]
# To streamline the signup process, we don't require email verification.
ACCOUNT_EMAIL_VERIFICATION = "optional"
ACCOUNT_CONFIRM_EMAIL_ON_GET = True
# Allow users to be logged in immediately after resetting their password.
ACCOUNT_LOGIN_ON_PASSWORD_RESET = True
# Allow login and logout via GET, skipping confirmation.
# Minor @todo would be to replace the login/logout buttons with POST requests, but low priority.
ACCOUNT_LOGOUT_ON_GET = True
SOCIALACCOUNT_LOGIN_ON_GET = True
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'
ACCOUNT_LOGOUT_REDIRECT_URL = '/'
ACCOUNT_SIGNUP_REDIRECT_URL = '/contribute?signup=true'

SOCIALACCOUNT_PROVIDERS = {
    "google": {
        # For each OAuth based provider, either add a ``SocialApp``
        # (``socialaccount`` app) containing the required client
        # credentials, or list them here:
        "APPS": [
            {
                "client_id": settings.google_client_id,
                "secret": settings.google_client_secret,
                "key": "",
                "settings": {
                    "scope": [
                        "profile",
                        "email",
                    ],
                    "auth_params": {
                        "access_type": "online",
                    },
                },
            },
        ],
        # The following provider-specific settings will be used for all apps:
        "SCOPE": [
            "profile",
            "email",
        ],
        "AUTH_PARAMS": {
            "access_type": "online",
        },
    }
}

## Crispy forms with DaisyUI styling.
CRISPY_ALLOWED_TEMPLATE_PACKS = 'daisyui'
CRISPY_TEMPLATE_PACK = 'daisyui'

# Uses Sentry for monitoring, if a URL is provided.
if getattr(settings, 'sentry_url', ''):
    sentry_sdk.init(
        dsn=settings.sentry_url,
        # Add data like request headers and IP for users,
        # see https://docs.sentry.io/platforms/python/data-management/data-collected/ for more info
        send_default_pii=True,
        # Set traces_sample_rate to 1.0 to capture 100% of transactions for tracing.
        traces_sample_rate=1.0,
    )
else:
    print("Sentry DSN not provided. Sentry monitoring is disabled.")

## Admin backend configuration using Jazzmin.
JAZZMIN_SETTINGS = {
    "site_title": "Traders Admin",
    "site_header": "Traders Admin",
    "site_brand": "Traders",
    "site_logo": "images/traders-icon.png",
    "login_logo": "icons/traders-icon.png",
    "welcome_sign": "Welcome to the Traders admin dashboard",
    "copyright": "Traders",
    "search_model": ["users.UserProfile", "lessons.Lesson"],

    "topmenu_links": [
        {"name": "Home", "url": "/", "permissions": ["auth.view_user"]},
        {"model": "auth.User"},
        {"app": "lessons"},
    ],

    "usermenu_links": [
        {"name": "GitHub", "url": "https://github.com/example.com", "new_window": True},
    ],

    "show_sidebar": True,
    "navigation_expanded": True,
    "hide_apps": [],
    "hide_models": [],

    "order_with_respect_to": [
        "core",
        "lessons",
        "skills",
        "auth",
        "users",
    ],

    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "users.UserProfile": "fas fa-id-badge",
        "feedback.Feedback": "fas fa-comments",
    },
    "default_icon_parents": "fas fa-folder",
    "default_icon_children": "fas fa-file",

    "related_modal_active": True,
    "changeform_format": "collapsible",
    "language_chooser": True,
}
